services:
  nbcovidbot:
    image: ghcr.io/iamsilk/nbcovidbot:latest
    container_name: nbcovidbot
    restart: unless-stopped
    volumes:
    - nbcovidbot:/data
    networks:
    - nbcovidbot

volumes:
  nbcovidbot:
    external:
      name: nbcovidbot

networks:
  nbcovidbot: {}