Token: "CHANGEME"

TimeZone: "Atlantic Standard Time"

Database:
  ConnectionStrings:
    Default: "Server=localhost; Database=NBCovidBot; User Id=username; Password=password"

Admins:
- "AnExampleAdmin#1234"

Commands:
  Prefix: "c!"