Token: "CHANGEME"

TimeZone: "America/Halifax"

CovidQuerySchedule: "5 15 * * *"

Commands:
  Prefix: "c!"

UserUpdates:
  Reactions:
    Subscribe: "✅"
    Unsubscribe: "❌"
  RoleName: "covid-updates"

Database:
  ConnectionStrings:
    Default: "Server=localhost; Database=NBCovidBot; User Id=username; Password=password"

Admins:
- "AnExampleAdmin#1234"
